In [14]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", array)

# Addition of 2 in all the elements of the array
print("Array after adding 2:", array + 2)

# Multiplication of 3 in all the elements of the array
print("Array after multiplying by 3:", array * 3)

# Division of all the elements of the array by 2
print("Array after dividing by 2:", array / 2)

Numpy Array: [1 2 3 4 5]
Array after adding 2: [3 4 5 6 7]
Array after multiplying by 3: [ 3  6  9 12 15]
Array after dividing by 2: [0.5 1.  1.5 2.  2.5]


In [15]:
# part a 
arr = np.array([1,2,3,6,4,5])
reverse_arr = arr[::-1]
print("Original Array:", arr)
print("Reversed Array:", reverse_arr)

# part b 
x = np.array([1,2,3,4,5,1,2,1,1,1])
values , counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]
print("Most Frequent Value of x :", most_frequent_value)
print("Indices of Most Frequent Value of x :", indices)

y = np.array([1,1,1,2,3,4,2,4,3,3])
values , counts = np.unique(y, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(y == most_frequent_value)[0]
print("Most Frequent Value of y :", most_frequent_value)
print("Indices of Most Frequent Value of y :", indices)

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]
Most Frequent Value of x : 1
Indices of Most Frequent Value of x : [0 5 7 8 9]
Most Frequent Value of y : 1
Indices of Most Frequent Value of y : [0 1 2]


In [16]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("1st row , 2nd column element of the array:", arr[0,1])
print("3rd row , 1st column element of the array:", arr[2,0])

1st row , 2nd column element of the array: 20
3rd row , 1st column element of the array: 70


In [17]:
import numpy as np 
Ishtpreet = np.linspace(10,100,25)
print("Array:" ,Ishtpreet)
print("dimensions of the array:",Ishtpreet.ndim)
print("Shape of the array:",Ishtpreet.shape)
print("Total elements of the array:",Ishtpreet.size )
print("Data type of the arry ",Ishtpreet.dtype)
print("Total no. of byte consumed :",Ishtpreet.nbytes)

#transpose of the array using reshape()
Transpose_arr = Ishtpreet.reshape(25,)
print("Transpose using reshape():", Transpose_arr)

#transpose using t attribute 
print("Transpose using t attribute:", Ishtpreet.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions of the array: 1
Shape of the array: (25,)
Total elements of the array: 25
Data type of the arry  float64
Total no. of byte consumed : 200
Transpose using reshape(): [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Transpose using t attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [18]:
import numpy as np
ucs420_Ishtpreet = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("Original Array:\n", ucs420_Ishtpreet)

print("Mean of the array:", np.mean(ucs420_Ishtpreet))
print ("Median of the array:", np.median(ucs420_Ishtpreet))
print("Max of the array",np.max(ucs420_Ishtpreet))
print("Min of the array",np.min(ucs420_Ishtpreet))
print("unique elements of the array ", np.unique(ucs420_Ishtpreet))

# reshaping the array to 4x3
reshaped_ucs420_Ishtpreet = ucs420_Ishtpreet.reshape(4,3)
print("Resaped Array ", reshaped_ucs420_Ishtpreet)

# resizing the array to 2x3
resized_ucs420_Ishtpreet = np.resize(ucs420_Ishtpreet, (2,3))
print("Resized Array ", resized_ucs420_Ishtpreet)

Original Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean of the array: 43.333333333333336
Median of the array: 37.5
Max of the array 90
Min of the array 10
unique elements of the array  [10 15 20 30 35 40 50 60 70 80 90]
Resaped Array  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array  [[10 20 30]
 [40 50 60]]
